//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aptekaEntities : DbContext
    {
        public static aptekaEntities _context;
        public aptekaEntities()
            : base("name=aptekaEntities")
        {
        }
        public static aptekaEntities GetContext()
        {
            if (_context == null)
            {
                _context = new aptekaEntities();
            }
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Serviceserv> Serviceserv { get; set; }
    }
}
