//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrdersID { get; set; }
        public Nullable<int> MedicinesID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Statusorders { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
