//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serviceserv
    {
        public int RegistrationID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> DateofServ { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
